/* ================= DỮ LIỆU BÓI TOÁN ================= */
/* ---------- TAROT 78 LÁ ---------- */
const TAROT = [
{n:"0. The Fool — Kẻ Khờ",g:"🌠",u:"Khởi đầu mới, tự do, niềm tin hồn nhiên vào cuộc đời; cứ bước đi dù chưa biết hết đường.",r:"Liều lĩnh thiếu suy nghĩ, ngây thơ bị lợi dụng, trốn tránh trách nhiệm."},
{n:"I. The Magician — Nhà Ảo Thuật",g:"🪄",u:"Đủ công cụ và tài năng để biến ý định thành hiện thực; thời điểm hành động, tập trung ý chí.",r:"Thao túng, khoác lác, tài năng bị lãng phí hoặc dùng sai mục đích."},
{n:"II. The High Priestess — Nữ Tư Tế",g:"🌙",u:"Trực giác, bí mật, tri thức ẩn; hãy lắng nghe tiếng nói bên trong thay vì lý trí bề mặt.",r:"Phớt lờ trực giác, bí mật bị che giấu gây hại, nông cạn."},
{n:"III. The Empress — Nữ Hoàng",g:"🌾",u:"Sung túc, nuôi dưỡng, sáng tạo, thai nghén (nghĩa đen lẫn nghĩa bóng); thành quả nở rộ.",r:"Bao bọc ngột ngạt, phụ thuộc, sáng tạo tắc nghẽn, bỏ bê bản thân."},
{n:"IV. The Emperor — Hoàng Đế",g:"🏛️",u:"Trật tự, kỷ luật, quyền lực vững chắc, người cha/người bảo trợ; xây nền móng lâu dài.",r:"Độc đoán, cứng nhắc, lạm quyền, hoặc thiếu kỷ luật tự thân."},
{n:"V. The Hierophant — Giáo Hoàng",g:"⛪",u:"Truyền thống, học hỏi từ thầy, khuôn khổ đạo đức, hôn lễ, tổ chức chính thống.",r:"Giáo điều, nổi loạn chống quy tắc, cần tìm con đường riêng."},
{n:"VI. The Lovers — Đôi Tình Nhân",g:"💞",u:"Tình yêu, sự hoà hợp sâu sắc, và một lựa chọn quan trọng từ trái tim và giá trị sống.",r:"Bất hoà, cám dỗ, lựa chọn sai vì thiếu trung thực với chính mình."},
{n:"VII. The Chariot — Cỗ Xe",g:"🏇",u:"Ý chí chiến thắng, kiểm soát hai thái cực để tiến lên; thành công nhờ quyết tâm.",r:"Mất phương hướng, hung hăng, tiến độ khựng lại vì thiếu kiểm soát."},
{n:"VIII. Strength — Sức Mạnh",g:"🦁",u:"Sức mạnh mềm: can đảm, kiên nhẫn, thuần hoá bản năng bằng lòng trắc ẩn.",r:"Tự ti, nóng giận bột phát, nghi ngờ sức mình."},
{n:"IX. The Hermit — Ẩn Sĩ",g:"🏮",u:"Rút lui để chiêm nghiệm, tìm câu trả lời bên trong, người thầy dẫn đường bằng ngọn đèn nhỏ.",r:"Cô lập quá mức, cô đơn, từ chối lời khuyên."},
{n:"X. Wheel of Fortune — Bánh Xe Số Phận",g:"🎡",u:"Vòng xoay vận mệnh, bước ngoặt, may mắn đến; điều duy nhất chắc chắn là thay đổi.",r:"Vận xui tạm thời, chống lại thay đổi, vòng lặp xấu cần phá."},
{n:"XI. Justice — Công Lý",g:"⚖️",u:"Công bằng, nhân quả, quyết định sáng suốt; sự thật sẽ được phân xử, giấy tờ pháp lý.",r:"Bất công, trốn tránh hậu quả, phán xét thiên lệch."},
{n:"XII. The Hanged Man — Người Treo Ngược",g:"🙃",u:"Tạm dừng tự nguyện, nhìn vấn đề từ góc ngược lại, buông để được; hy sinh có mục đích.",r:"Trì hoãn vô ích, hy sinh không được ghi nhận, mắc kẹt."},
{n:"XIII. Death — Cái Chết",g:"🦋",u:"Kết thúc một chu kỳ để tái sinh; buông bỏ cái cũ dứt khoát, chuyển hoá sâu sắc. Hiếm khi là cái chết nghĩa đen.",r:"Níu kéo cái đã hết, sợ thay đổi, chuyển giao kéo dài đau đớn."},
{n:"XIV. Temperance — Tiết Chế",g:"🏺",u:"Cân bằng, điều độ, kiên nhẫn pha trộn các yếu tố; chữa lành từ từ, trung dung.",r:"Mất cân bằng, quá đà, thiếu kiên nhẫn, xung đột nội tâm."},
{n:"XV. The Devil — Ác Quỷ",g:"⛓️",u:"Ràng buộc, nghiện, cám dỗ vật chất; xiềng xích thực ra lỏng — bạn có thể tháo ra.",r:"Bắt đầu thoát khỏi ràng buộc, nhận diện được cái bẫy, giải phóng."},
{n:"XVI. The Tower — Tòa Tháp",g:"🌩️",u:"Sụp đổ đột ngột của nền móng giả; sự thật bùng nổ, giải phóng dữ dội nhưng cần thiết.",r:"Né tránh sụp đổ tất yếu, khủng hoảng kéo dài, sợ thay đổi tận gốc."},
{n:"XVII. The Star — Ngôi Sao",g:"⭐",u:"Hy vọng, chữa lành, cảm hứng sau giông bão; niềm tin được hồi phục, hào phóng.",r:"Mất niềm tin, chán nản, cảm hứng cạn kiệt — cần tự nạp lại."},
{n:"XVIII. The Moon — Mặt Trăng",g:"🌕",u:"Ảo ảnh, trực giác, nỗi sợ vô hình, giấc mơ; mọi thứ chưa như vẻ ngoài, hãy đi chậm.",r:"Sương mù tan dần, sự thật lộ ra, vượt qua lo âu."},
{n:"XIX. The Sun — Mặt Trời",g:"☀️",u:"Niềm vui, thành công rực rỡ, sức sống, trẻ thơ; câu trả lời tích cực rõ ràng.",r:"Niềm vui bị trì hoãn, tự mãn, lạc quan thiếu thực tế nhẹ."},
{n:"XX. Judgement — Phán Xét",g:"🎺",u:"Thức tỉnh, tổng kết một giai đoạn đời, tha thứ và tái sinh; tiếng gọi sứ mệnh.",r:"Tự phán xét khắc nghiệt, trì hoãn quyết định lớn, không nghe tiếng gọi."},
{n:"XXI. The World — Thế Giới",g:"🌍",u:"Hoàn tất viên mãn, thành tựu, hội nhập, du hành; một vòng tròn khép lại đẹp đẽ.",r:"Dang dở, thiếu bước cuối, cần khép lại điều còn treo."},
{n:"Át Gậy (Ace of Wands)",g:"🪄",u:"Tia lửa khởi đầu: cảm hứng, cơ hội mới đầy năng lượng.",r:"Trì hoãn, ý tưởng chưa chín, thiếu động lực."},
{n:"2 Gậy (Two of Wands)",g:"🪄",u:"Lên kế hoạch, nhìn xa, quyết định mở rộng lãnh thổ.",r:"Sợ bước ra khỏi vùng an toàn, kế hoạch dở dang."},
{n:"3 Gậy (Three of Wands)",g:"🪄",u:"Thuyền đã ra khơi: chờ thành quả, tầm nhìn dài hạn, mở rộng.",r:"Chậm trễ, tầm nhìn hẹp, trở ngại từ bên ngoài."},
{n:"4 Gậy (Four of Wands)",g:"🪄",u:"Ăn mừng, mái ấm, lễ hội, cột mốc hạnh phúc.",r:"Bất ổn trong nhà, lễ bị hoãn, thiếu cảm giác thuộc về."},
{n:"5 Gậy (Five of Wands)",g:"🪄",u:"Cạnh tranh, va chạm ý kiến, thử sức lành mạnh.",r:"Xung đột vô nghĩa, né tránh tranh luận cần thiết."},
{n:"6 Gậy (Six of Wands)",g:"🪄",u:"Chiến thắng được công nhận, vinh quang trở về, tự tin.",r:"Kiêu ngạo, thành công bị nghi ngờ, thất vọng vì không được ghi nhận."},
{n:"7 Gậy (Seven of Wands)",g:"🪄",u:"Giữ vững lập trường trên cao điểm, phòng thủ can trường.",r:"Đuối sức, bị lấn át, muốn buông xuôi."},
{n:"8 Gậy (Eight of Wands)",g:"🪄",u:"Tốc độ, tin tức bay đến, mọi việc tăng tốc, du lịch.",r:"Chậm trễ, tin xấu, hấp tấp gây rối."},
{n:"9 Gậy (Nine of Wands)",g:"🪄",u:"Kiên cường ở chặng cuối, cảnh giác, còn một nhịp nữa là xong.",r:"Kiệt sức, phòng thủ quá mức, hoang tưởng bị hại."},
{n:"10 Gậy (Ten of Wands)",g:"🪄",u:"Gánh nặng thành công, ôm đồm; sắp đến đích nhưng quá tải.",r:"Cần buông bớt, uỷ quyền, giải phóng gánh nặng."},
{n:"Bồi Gậy (Page of Wands)",g:"🪄",u:"Người trẻ nhiệt huyết, tin tức về cơ hội mới, tinh thần khám phá.",r:"Bồng bột, tin trễ, nhiệt tình sớm nở tối tàn."},
{n:"Kỵ Sĩ Gậy (Knight of Wands)",g:"🪄",u:"Hành động táo bạo, phiêu lưu, đam mê rực lửa.",r:"Hấp tấp, nóng nảy, bỏ dở giữa chừng."},
{n:"Hoàng Hậu Gậy (Queen of Wands)",g:"🪄",u:"Người phụ nữ quyến rũ, tự tin, ấm áp, truyền cảm hứng.",r:"Ghen tuông, đòi hỏi, tự tin thành tự cao."},
{n:"Vua Gậy (King of Wands)",g:"🪄",u:"Nhà lãnh đạo có tầm nhìn, doanh nhân, người truyền lửa.",r:"Độc đoán, kỳ vọng phi thực tế, nóng vội."},
{n:"Át Cốc (Ace of Cups)",g:"🏆",u:"Tình cảm mới tràn đầy, trái tim rộng mở, trực giác, tin vui tình cảm.",r:"Cảm xúc bị kìm nén, tình cảm không được đáp lại."},
{n:"2 Cốc (Two of Cups)",g:"🏆",u:"Kết nối đôi lứa, đối tác tâm đầu ý hợp, hoà giải.",r:"Rạn nứt, mất cân bằng cho–nhận, chia tay nhẹ."},
{n:"3 Cốc (Three of Cups)",g:"🏆",u:"Bạn bè, ăn mừng, cộng đồng nâng đỡ nhau.",r:"Tiệc tùng quá đà, người thứ ba, nhóm bạn rạn nứt."},
{n:"4 Cốc (Four of Cups)",g:"🏆",u:"Chán chường, thờ ơ với cơ hội trước mặt; hãy nhìn lại món quà đang được trao.",r:"Tỉnh ra khỏi trì trệ, chấp nhận lời mời mới."},
{n:"5 Cốc (Five of Cups)",g:"🏆",u:"Tiếc nuối mất mát; ba cốc đổ nhưng hai cốc vẫn còn sau lưng.",r:"Chấp nhận, tha thứ, bước tiếp sau tổn thương."},
{n:"6 Cốc (Six of Cups)",g:"🏆",u:"Ký ức tuổi thơ, người xưa trở lại, quà tặng ngọt ngào, hoài niệm.",r:"Mắc kẹt trong quá khứ, cần sống với hiện tại."},
{n:"7 Cốc (Seven of Cups)",g:"🏆",u:"Nhiều lựa chọn như mơ, ảo tưởng; cần tỉnh táo chọn một.",r:"Hết ảo tưởng, quyết định rõ ràng, thực tế trở lại."},
{n:"8 Cốc (Eight of Cups)",g:"🏆",u:"Rời bỏ điều không còn nuôi dưỡng mình để đi tìm ý nghĩa sâu hơn.",r:"Sợ rời đi, quay lại thứ đã bỏ, trốn tránh."},
{n:"9 Cốc (Nine of Cups)",g:"🏆",u:"Lá bài điều ước: mãn nguyện, hưởng thụ thành quả.",r:"Thoả mãn hời hợt, tham lam, ước muốn chưa thành."},
{n:"10 Cốc (Ten of Cups)",g:"🏆",u:"Gia đình hạnh phúc, viên mãn tình cảm, cầu vồng sau mưa.",r:"Bất hoà gia đình, hạnh phúc bề ngoài, giá trị lệch nhau."},
{n:"Bồi Cốc (Page of Cups)",g:"🏆",u:"Tin nhắn tình cảm, sáng tạo bay bổng, tâm hồn mơ mộng.",r:"Nhạy cảm quá mức, tin thất thiệt, mơ mộng viển vông."},
{n:"Kỵ Sĩ Cốc (Knight of Cups)",g:"🏆",u:"Người mang lời tỏ tình/lời mời lãng mạn, chàng thơ đa cảm.",r:"Hứa hẹn suông, thất thường, lãng mạn giả."},
{n:"Hoàng Hậu Cốc (Queen of Cups)",g:"🏆",u:"Người phụ nữ trực giác mạnh, bao dung, thấu cảm sâu sắc.",r:"Cảm xúc nhấn chìm, phụ thuộc tình cảm, dễ bị lung lay."},
{n:"Vua Cốc (King of Cups)",g:"🏆",u:"Người đàn ông điềm đạm, làm chủ cảm xúc, cố vấn nhân hậu.",r:"Đè nén cảm xúc, thao túng tình cảm, lạnh lùng."},
{n:"Át Kiếm (Ace of Swords)",g:"⚔️",u:"Sự thật sắc bén, ý tưởng đột phá, quyết định dứt khoát, thắng lý.",r:"Suy nghĩ rối, sự thật bị bóp méo, quyết định vội."},
{n:"2 Kiếm (Two of Swords)",g:"⚔️",u:"Bế tắc lựa chọn, bịt mắt trước sự thật; cần gỡ băng che mắt để quyết.",r:"Bế tắc vỡ ra, thông tin lộ diện, buộc phải chọn."},
{n:"3 Kiếm (Three of Swords)",g:"⚔️",u:"Trái tim tổn thương, sự thật đau lòng, chia ly.",r:"Vết thương đang lành, tha thứ, học được bài học."},
{n:"4 Kiếm (Four of Swords)",g:"⚔️",u:"Nghỉ ngơi chủ động, hồi phục, tạm rút khỏi chiến trận.",r:"Kiệt sức vì không chịu nghỉ, hoặc trì trệ quá lâu."},
{n:"5 Kiếm (Five of Swords)",g:"⚔️",u:"Thắng mà mất: xung đột thắng bằng mọi giá, tổn thất quan hệ.",r:"Buông cuộc chiến vô nghĩa, làm hoà, rút lui khôn ngoan."},
{n:"6 Kiếm (Six of Swords)",g:"⚔️",u:"Chuyển bến sang vùng nước yên hơn; rời khó khăn, hành trình chữa lành.",r:"Chưa dứt được quá khứ, chuyến đi trắc trở."},
{n:"7 Kiếm (Seven of Swords)",g:"⚔️",u:"Mưu mẹo, hành động một mình, có kẻ thiếu trung thực quanh bạn.",r:"Sự dối trá bại lộ, tự lừa mình, nên minh bạch."},
{n:"8 Kiếm (Eight of Swords)",g:"⚔️",u:"Tự trói mình bằng suy nghĩ giới hạn; lối ra có sẵn nếu dám nhìn.",r:"Tự giải thoát, nhìn ra quyền lựa chọn của mình."},
{n:"9 Kiếm (Nine of Swords)",g:"⚔️",u:"Lo âu mất ngủ, nỗi sợ phóng đại về đêm; thực tế ít tệ hơn tưởng.",r:"Lo âu dịu xuống, tìm được người giãi bày, hy vọng."},
{n:"10 Kiếm (Ten of Swords)",g:"⚔️",u:"Chạm đáy, kết thúc đau nhưng dứt điểm; bình minh đã ở chân trời.",r:"Hồi phục sau đổ vỡ, sống sót, bài học được giữ lại."},
{n:"Bồi Kiếm (Page of Swords)",g:"⚔️",u:"Tò mò, tin tức cần kiểm chứng, người trẻ lanh lợi hay dò xét.",r:"Nói không giữ lời, do thám, lời nói làm tổn thương."},
{n:"Kỵ Sĩ Kiếm (Knight of Swords)",g:"⚔️",u:"Lao thẳng vào mục tiêu, tranh luận sắc bén, hành động thần tốc.",r:"Hấp tấp gây đổ vỡ, lời nói như dao, thiếu kế hoạch."},
{n:"Hoàng Hậu Kiếm (Queen of Swords)",g:"⚔️",u:"Người phụ nữ sắc sảo, độc lập, nói thẳng, phán đoán công tâm.",r:"Lạnh lùng cay nghiệt, thành kiến, cô lập."},
{n:"Vua Kiếm (King of Swords)",g:"⚔️",u:"Người đàn ông trí tuệ, quyền uy về luật lệ/chuyên môn, phán quyết công minh.",r:"Lạm dụng trí tuệ, độc tài, phán xét lạnh lùng."},
{n:"Át Tiền (Ace of Pentacles)",g:"🪙",u:"Hạt giống tài lộc: cơ hội tiền bạc, công việc, sức khoẻ vững chắc mới.",r:"Cơ hội vụt mất, khởi đầu tài chính thiếu nền."},
{n:"2 Tiền (Two of Pentacles)",g:"🪙",u:"Tung hứng nhiều việc, cân đối thu chi, linh hoạt thích nghi.",r:"Quá tải, mất cân đối tài chính, ưu tiên lộn xộn."},
{n:"3 Tiền (Three of Pentacles)",g:"🪙",u:"Hợp tác chuyên môn, tay nghề được công nhận, xây dựng cùng nhau.",r:"Làm việc nhóm trục trặc, thiếu ghi nhận, làm ẩu."},
{n:"4 Tiền (Four of Pentacles)",g:"🪙",u:"Giữ chặt tài sản, ổn định nhưng khư khư; an toàn thành kìm kẹp.",r:"Buông tay chi tiêu, hào phóng trở lại, hoặc mất kiểm soát tiền."},
{n:"5 Tiền (Five of Pentacles)",g:"🪙",u:"Khó khăn vật chất, cảm giác bị bỏ rơi; cửa giúp đỡ ở ngay cạnh mà chưa thấy.",r:"Khó khăn qua đi, được cứu giúp, hồi phục tài chính."},
{n:"6 Tiền (Six of Pentacles)",g:"🪙",u:"Cho và nhận công bằng, quà tặng, giúp đỡ tài chính.",r:"Cho vay khó đòi, bố thí kèm điều kiện, nhận bất công."},
{n:"7 Tiền (Seven of Pentacles)",g:"🪙",u:"Kiên nhẫn chờ cây ra trái, đánh giá lại khoản đầu tư.",r:"Sốt ruột, đầu tư không sinh lời, bỏ cuộc sớm."},
{n:"8 Tiền (Eight of Pentacles)",g:"🪙",u:"Rèn nghề miệt mài, học kỹ năng, chất lượng từng chi tiết.",r:"Làm việc máy móc thiếu tâm, tay nghề dậm chân."},
{n:"9 Tiền (Nine of Pentacles)",g:"🪙",u:"Độc lập tài chính, hưởng thành quả một cách sang trọng, tự tại.",r:"Phụ thuộc vật chất, thành quả thiếu bền, tiêu xài quá tay."},
{n:"10 Tiền (Ten of Pentacles)",g:"🪙",u:"Của cải gia tộc, thừa kế, nền tảng lâu dài cho con cháu.",r:"Tranh chấp tài sản gia đình, nền tảng lung lay."},
{n:"Bồi Tiền (Page of Pentacles)",g:"🪙",u:"Tin tức về tiền/học hành, người trẻ chăm chỉ, cơ hội học nghề.",r:"Lười nhác, tin xấu tài chính, kế hoạch không thực tế."},
{n:"Kỵ Sĩ Tiền (Knight of Pentacles)",g:"🪙",u:"Bền bỉ, đáng tin, tiến chậm mà chắc, làm tròn bổn phận.",r:"Ù lì, nhàm chán, cầu toàn đến trì trệ."},
{n:"Hoàng Hậu Tiền (Queen of Pentacles)",g:"🪙",u:"Người phụ nữ đảm đang, thực tế, vun vén tổ ấm lẫn tài chính.",r:"Ôm đồm việc nhà–việc tiền, bỏ bê bản thân."},
{n:"Vua Tiền (King of Pentacles)",g:"🪙",u:"Doanh nhân thành đạt, vững vàng, hào phóng, chạm đâu ra tiền đó.",r:"Tham vật chất, bảo thủ, dùng tiền để kiểm soát."}
];

/* ---------- LENORMAND 36 LÁ ---------- */
const LENORMAND = [
{i:1,n:"Kỵ Sĩ (Rider)",g:"🐎",k:"tin tức, người đến",m:"Tin tức đang trên đường tới, một vị khách hoặc chuyển động mới; mọi việc bắt đầu nhúc nhích."},
{i:2,n:"Cỏ Ba Lá (Clover)",g:"🍀",k:"may mắn nhỏ",m:"May mắn nhỏ, cơ hội thoáng qua — hãy nắm nhanh; niềm vui nhẹ nhõm, không kéo dài."},
{i:3,n:"Con Tàu (Ship)",g:"⛵",k:"hành trình, thương mại",m:"Chuyến đi, khoảng cách, giao thương; điều tốt đến từ xa hoặc cần bạn dịch chuyển."},
{i:4,n:"Ngôi Nhà (House)",g:"🏠",k:"gia đình, ổn định",m:"Mái ấm, gia đình, sự an toàn nền tảng; chuyện nhà cửa, người thân thiết."},
{i:5,n:"Cái Cây (Tree)",g:"🌳",k:"sức khoẻ, gốc rễ",m:"Sức khoẻ, sự phát triển chậm mà sâu, gốc rễ tâm linh; điều gì đó cần thời gian bén rễ."},
{i:6,n:"Đám Mây (Clouds)",g:"☁️",k:"mơ hồ, rắc rối",m:"Sự mù mờ, hoang mang, rắc rối tạm thời; đừng quyết định lớn khi trời chưa quang."},
{i:7,n:"Con Rắn (Snake)",g:"🐍",k:"cám dỗ, người phụ nữ khéo",m:"Đường vòng, sự phản bội hoặc người khôn khéo có ý đồ; cẩn trọng nhưng cũng là trí tuệ."},
{i:8,n:"Quan Tài (Coffin)",g:"⚰️",k:"kết thúc, ốm",m:"Một điều kết thúc, giai đoạn ngủ đông, bệnh nhẹ; khép lại để chôn cất và đi tiếp."},
{i:9,n:"Bó Hoa (Bouquet)",g:"💐",k:"quà, lời mời",m:"Món quà, lời mời, niềm vui xã giao, sự trân trọng; điều dễ thương đang đến."},
{i:10,n:"Lưỡi Hái (Scythe)",g:"🪓",k:"cắt đứt, đột ngột",m:"Quyết định cắt đứt, sự việc đột ngột, nguy cơ tai nạn nhỏ; nhanh, dứt khoát, không báo trước."},
{i:11,n:"Cây Roi (Whip)",g:"〰️",k:"tranh cãi, lặp lại",m:"Cãi vã, xung đột lặp đi lặp lại, tập luyện; chuyện nóng nảy trong lời nói."},
{i:12,n:"Bầy Chim (Birds)",g:"🐦",k:"trò chuyện, lo lắng",m:"Những cuộc nói chuyện, điện thoại, xì xào; đôi khi là lo lắng vụn vặt; chuyện đến theo cặp."},
{i:13,n:"Đứa Trẻ (Child)",g:"🧒",k:"khởi đầu, ngây thơ",m:"Khởi đầu nhỏ, đứa trẻ, sự hồn nhiên, điều gì đó còn non; bắt đầu từ quy mô nhỏ."},
{i:14,n:"Con Cáo (Fox)",g:"🦊",k:"khôn ranh, công việc",m:"Sự khéo léo sinh tồn, công việc mưu sinh; cảnh giác người giả vờ; tự lo cho mình trước."},
{i:15,n:"Con Gấu (Bear)",g:"🐻",k:"quyền lực, tiền lớn",m:"Sếp, người có quyền, nguồn tài chính lớn, sức mạnh che chở; cũng là sự ghen tị."},
{i:16,n:"Ngôi Sao (Stars)",g:"⭐",k:"hy vọng, định hướng",m:"Hy vọng, cảm hứng, con đường sáng rõ; kế hoạch dài hạn được dẫn lối."},
{i:17,n:"Con Cò (Stork)",g:"🕊️",k:"thay đổi, chuyển nhà",m:"Sự thay đổi tích cực, chuyển chỗ ở, tin về em bé; mọi thứ được nâng cấp."},
{i:18,n:"Con Chó (Dog)",g:"🐕",k:"bạn trung thành",m:"Tình bạn, sự trung thành, người đáng tin cậy đứng về phía bạn."},
{i:19,n:"Tòa Tháp (Tower)",g:"🗼",k:"cơ quan, cô độc",m:"Cơ quan, tổ chức, pháp lý, ranh giới; tầm nhìn xa nhưng cũng là sự đơn độc."},
{i:20,n:"Khu Vườn (Garden)",g:"🌸",k:"đám đông, sự kiện",m:"Sự kiện xã hội, cộng đồng, nơi công cộng; chuyện của bạn được nhiều người biết."},
{i:21,n:"Ngọn Núi (Mountain)",g:"⛰️",k:"trở ngại, trì hoãn",m:"Trở ngại lớn, sự trì hoãn, đối thủ nặng ký; cần sức bền hoặc đường vòng."},
{i:22,n:"Ngã Rẽ (Crossroad)",g:"🛤️",k:"lựa chọn",m:"Ngã ba đường, nhiều phương án; phải tự chọn, không ai chọn thay."},
{i:23,n:"Con Chuột (Mice)",g:"🐭",k:"hao mòn, mất mát",m:"Sự hao hụt âm thầm, stress gặm nhấm, mất trộm vặt; kiểm tra chỗ rò rỉ."},
{i:24,n:"Trái Tim (Heart)",g:"❤️",k:"tình yêu",m:"Tình yêu, sự rung động chân thành, lòng trắc ẩn; trái tim lên tiếng."},
{i:25,n:"Chiếc Nhẫn (Ring)",g:"💍",k:"cam kết, hợp đồng",m:"Hôn ước, hợp đồng, cam kết ràng buộc, vòng lặp; điều được ký kết."},
{i:26,n:"Quyển Sách (Book)",g:"📕",k:"bí mật, tri thức",m:"Bí mật chưa mở, việc học hành, dự án còn kín; kiến thức là chìa khoá."},
{i:27,n:"Lá Thư (Letter)",g:"✉️",k:"văn bản, giấy tờ",m:"Thư từ, tin nhắn, giấy tờ, chứng từ; thông tin dạng văn bản đang đến."},
{i:28,n:"Quý Ông (Man)",g:"🤵",k:"người đàn ông",m:"Người đàn ông trong câu hỏi (bản thân hoặc đối tượng); các lá quanh mô tả anh ấy."},
{i:29,n:"Quý Bà (Woman)",g:"👩",k:"người phụ nữ",m:"Người phụ nữ trong câu hỏi (bản thân hoặc đối tượng); các lá quanh mô tả cô ấy."},
{i:30,n:"Bông Huệ (Lily)",g:"🌷",k:"bình yên, người lớn tuổi",m:"Sự bình yên chín chắn, người lớn tuổi nâng đỡ, sự thanh khiết; mùa đông êm đềm."},
{i:31,n:"Mặt Trời (Sun)",g:"☀️",k:"thành công, năng lượng",m:"Thành công rực rỡ, hạnh phúc, sinh lực dồi dào; lá bài tốt bậc nhất bộ."},
{i:32,n:"Mặt Trăng (Moon)",g:"🌙",k:"danh tiếng, cảm xúc",m:"Danh tiếng, sự công nhận, đời sống cảm xúc và trực giác; được người khác nhìn thấy."},
{i:33,n:"Chìa Khóa (Key)",g:"🗝️",k:"giải pháp, chắc chắn",m:"Câu trả lời chắc chắn «có», cánh cửa mở ra, giải pháp; điều quan trọng cần chú ý."},
{i:34,n:"Con Cá (Fish)",g:"🐟",k:"tiền bạc, dồi dào",m:"Dòng tiền, kinh doanh, sự dồi dào trôi chảy; nhiều nguồn, nhiều cơ hội."},
{i:35,n:"Mỏ Neo (Anchor)",g:"⚓",k:"ổn định lâu dài",m:"Sự ổn định, công việc lâu dài, bến đỗ; kiên trì sẽ giữ được điều bền vững."},
{i:36,n:"Thập Giá (Cross)",g:"✝️",k:"gánh nặng, định mệnh",m:"Thử thách phải mang, nỗi khổ có hạn kỳ, bài học định mệnh; nặng nhưng sẽ qua."}
];

/* ---------- BÀI TÂY 52 LÁ ---------- */
const BAITAY = [
{n:"Át Cơ",g:"A♥",m:"Tin vui lớn về tình cảm, mái ấm; khởi đầu yêu thương, tiệc tùng trong nhà."},
{n:"2 Cơ",g:"2♥",m:"Hẹn hò, kết đôi, sự đồng lòng của hai người."},
{n:"3 Cơ",g:"3♥",m:"Cần cẩn trọng trong quyết định tình cảm; niềm vui nhóm bạn."},
{n:"4 Cơ",g:"4♥",m:"Thay đổi trong tình cảm, chuyến đi vì người thân, cưới hỏi muộn."},
{n:"5 Cơ",g:"5♥",m:"Ghen tuông nhẹ, do dự; đừng quyết khi đang xúc động."},
{n:"6 Cơ",g:"6♥",m:"Ký ức đẹp, người cũ ghé lại, sự bao dung."},
{n:"7 Cơ",g:"7♥",m:"Mơ mộng, thất thường; ai đó không đáng tin hoàn toàn trong tình cảm."},
{n:"8 Cơ",g:"8♥",m:"Lời mời, buổi tiệc, chuyến thăm mang niềm vui."},
{n:"9 Cơ",g:"9♥",m:"Lá bài điều ước — mong muốn thành hiện thực."},
{n:"10 Cơ",g:"10♥",m:"Hạnh phúc viên mãn, may mắn lớn, hoá giải các lá xấu bên cạnh."},
{n:"Bồi Cơ",g:"J♥",m:"Người trẻ đa cảm, bạn thân, người mang tin tình cảm."},
{n:"Đầm Cơ",g:"Q♥",m:"Người phụ nữ tốt bụng, thuỷ chung, hết lòng vì gia đình."},
{n:"Già Cơ",g:"K♥",m:"Người đàn ông nhân hậu, che chở, cố vấn đáng tin."},
{n:"Át Rô",g:"A♦",m:"Tin tức, thư từ về tiền bạc; nhẫn hoặc quà giá trị."},
{n:"2 Rô",g:"2♦",m:"Chuyện tiền bạc đôi bên, giao dịch nhỏ thuận lợi."},
{n:"3 Rô",g:"3♦",m:"Tranh cãi vì tiền hoặc giấy tờ; cần rõ ràng văn bản."},
{n:"4 Rô",g:"4♦",m:"Tài chính ổn định lại; khoản tiền cũ quay về."},
{n:"5 Rô",g:"5♦",m:"Tin vui bất ngờ về tiền, thành công trong dự tính."},
{n:"6 Rô",g:"6♦",m:"Cẩn thận chi tiêu; cho vay khó đòi."},
{n:"7 Rô",g:"7♦",m:"Lời đàm tiếu về tiền; may rủi cờ bạc — nên tránh."},
{n:"8 Rô",g:"8♦",m:"Chuyến đi ngắn liên quan công việc, tiền về theo đường xa."},
{n:"9 Rô",g:"9♦",m:"Bất ngờ về tài chính, cơ hội kinh doanh mới."},
{n:"10 Rô",g:"10♦",m:"Khoản tiền lớn, thành công vật chất, chuyến đi xa sinh lợi."},
{n:"Bồi Rô",g:"J♦",m:"Người mang tin, nhân viên công vụ; tin về giấy tờ, tiền bạc."},
{n:"Đầm Rô",g:"Q♦",m:"Người phụ nữ sắc sảo chuyện làm ăn, thích giao du, hơi thị phi."},
{n:"Già Rô",g:"K♦",m:"Người đàn ông quyền thế về tài chính, đối tác lớn; thực dụng."},
{n:"Át Chuồn",g:"A♣",m:"Tin vui về công việc, tài lộc; khởi sự hanh thông."},
{n:"2 Chuồn",g:"2♣",m:"Hợp tác, trở ngại nhỏ được gỡ nhờ bạn bè."},
{n:"3 Chuồn",g:"3♣",m:"Kết quả tốt sau vài lần thử; hôn nhân có lợi."},
{n:"4 Chuồn",g:"4♣",m:"Sự trì hoãn, thay đổi kế hoạch; đề phòng thất hứa."},
{n:"5 Chuồn",g:"5♣",m:"Bạn mới, liên minh mới; tin từ nơi xa."},
{n:"6 Chuồn",g:"6♣",m:"Kinh doanh thuận, được giúp đỡ đúng lúc."},
{n:"7 Chuồn",g:"7♣",m:"May mắn nhỏ về tiền; cẩn thận người khác giới gây rắc rối."},
{n:"8 Chuồn",g:"8♣",m:"Ham muốn vội vàng về tiền; đầu tư cần tính kỹ."},
{n:"9 Chuồn",g:"9♣",m:"Thành tựu, di sản, cơ hội mới từ người quen."},
{n:"10 Chuồn",g:"10♣",m:"May mắn lớn, tiền đến bất ngờ, chuyến đi thành công."},
{n:"Bồi Chuồn",g:"J♣",m:"Người trẻ nhiệt tình, đáng tin trong công việc; tin tốt nghề nghiệp."},
{n:"Đầm Chuồn",g:"Q♣",m:"Người phụ nữ tự tin, giỏi giang, sẵn lòng giúp đỡ."},
{n:"Già Chuồn",g:"K♣",m:"Người đàn ông chính trực, bạn làm ăn trung thành, quý nhân."},
{n:"Át Bích",g:"A♠",m:"Quyết định hệ trọng; kết thúc để bắt đầu; cần thận trọng tối đa."},
{n:"2 Bích",g:"2♠",m:"Chia rẽ, lời nói hai lòng; đề phòng lừa dối."},
{n:"3 Bích",g:"3♠",m:"Nước mắt, chia ly ngắn, hiểu lầm cần nói rõ."},
{n:"4 Bích",g:"4♠",m:"Ốm nhẹ, mệt mỏi; nên nghỉ ngơi, hoãn việc lớn."},
{n:"5 Bích",g:"5♠",m:"Cãi vã, xáo trộn; thắng thua đều thiệt — nên nhịn."},
{n:"6 Bích",g:"6♠",m:"Cải thiện chậm; rời khỏi khó khăn từng bước."},
{n:"7 Bích",g:"7♠",m:"Mất mát nhỏ, lời khuyên nên thay đổi hướng đi."},
{n:"8 Bích",g:"8♠",m:"Cản trở, tin không vui; cẩn thận với cam kết mới."},
{n:"9 Bích",g:"9♠",m:"Lo âu, tin xấu, trì hoãn; đừng quyết định trong lo sợ."},
{n:"10 Bích",g:"10♠",m:"Gánh nặng, đêm tối trước bình minh; khép lại một chương."},
{n:"Bồi Bích",g:"J♠",m:"Người trẻ mưu mẹo, kẻ dò xét; tin tức cần kiểm chứng."},
{n:"Đầm Bích",g:"Q♠",m:"Người phụ nữ sắc lạnh, goá bụa hoặc đơn độc; có thể đố kỵ."},
{n:"Già Bích",g:"K♠",m:"Người đàn ông quyền lực nghiêm khắc, pháp lý; đối thủ đáng gờm."}
];

/* ---------- KINH DỊCH 64 QUẺ (theo số Văn Vương) ---------- */
const KINHDICH = {
1:{n:"Thuần Càn",y:"Trời mạnh mẽ, sáng tạo thuần khiết. Nguyên–Hanh–Lợi–Trinh: mọi sự hanh thông nếu giữ chính đạo.",a:"Thời điểm của người quân tử tự cường không nghỉ. Cứ tiến hành việc lớn, nhưng tránh kiêu căng khi lên đỉnh."},
2:{n:"Thuần Khôn",y:"Đất bao dung, nâng đỡ vạn vật. Thành công đến nhờ mềm mỏng, thuận theo, không tranh đi trước.",a:"Đừng dẫn đầu lúc này, hãy hỗ trợ và lắng nghe. Kiên trì như đất chở, lợi về hướng Tây Nam (bạn bè giúp đỡ)."},
3:{n:"Thủy Lôi Truân",y:"Gian nan buổi đầu, như mầm cây đội đất. Hỗn độn nhưng chứa sức sống mãnh liệt.",a:"Đừng nôn nóng mở rộng; củng cố nội bộ, tìm người phụ tá tốt. Khó khăn hiện tại là cơn đau sinh nở."},
4:{n:"Sơn Thủy Mông",y:"Trẻ dại, mông muội, chưa rõ đường. Cần được khai sáng bởi thầy, bởi kinh nghiệm.",a:"Hãy khiêm tốn học hỏi, tìm thầy mà hỏi — nhưng hỏi lần đầu thì được đáp, hỏi dai dẳng vì nghi ngờ thì không."},
5:{n:"Thủy Thiên Nhu",y:"Chờ đợi có niềm tin. Mây đã lên trời nhưng mưa chưa rơi; thời cơ chưa chín.",a:"Không phải bất động mà là chờ trong tư thế sẵn sàng. Ăn uống, dưỡng sức, giữ vững lòng tin; vượt sông lớn sẽ lợi khi đúng lúc."},
6:{n:"Thiên Thủy Tụng",y:"Tranh chấp, kiện tụng. Hai bên căng nhau như trời với nước, đi ngược chiều.",a:"Dừng ở giữa chừng thì tốt, theo đuổi đến cùng thì xấu. Tìm người công chính phân xử, tránh vượt sông lớn lúc này."},
7:{n:"Địa Thủy Sư",y:"Quân đội, tổ chức lực lượng. Việc lớn cần kỷ luật và người chỉ huy lão luyện.",a:"Chọn người dẫn dắt xứng đáng, danh chính ngôn thuận rồi hãy hành động. Ra quân có chính nghĩa thì thắng."},
8:{n:"Thủy Địa Tỷ",y:"Thân cận, liên kết. Nước trên đất thấm vào nhau; các bên nương tựa quanh một trung tâm.",a:"Chủ động kết giao sớm, ai đến muộn sẽ lỡ thời. Chọn đúng người mà gắn bó, trung thành với liên minh."},
9:{n:"Phong Thiên Tiểu Súc",y:"Tích nhỏ, sức chứa còn ít. Mây dày mà chưa mưa; kìm hãm nhẹ, thành tựu nhỏ.",a:"Chưa làm được việc lớn thì hoàn thiện việc nhỏ. Tích lũy từng chút, trau dồi đức độ, chờ mưa xuống."},
10:{n:"Thiên Trạch Lý",y:"Dẫm lên đuôi hổ mà hổ không cắn. Đi trong nguy hiểm bằng lễ độ và cẩn trọng.",a:"Giữ đúng phép tắc, khiêm cung với người trên kẻ dưới thì việc nguy thành an. Biết mình biết người."},
11:{n:"Địa Thiên Thái",y:"Thái hoà, thịnh vượng. Trời đất giao hoà, trên dưới thông suốt; nhỏ đi lớn đến.",a:"Thời vận rất tốt — hãy mở rộng, kết nối, gieo trồng. Nhưng nhớ trong thái có bĩ: đừng phung phí vận may."},
12:{n:"Thiên Địa Bĩ",y:"Bế tắc, trời đất không giao. Người nhỏ nhen đắc thế, người quân tử nên ẩn mình.",a:"Không phải lúc phô trương hay đầu tư lớn. Thu mình giữ đức, chờ bĩ cực thái lai — vòng xoay sẽ đổi."},
13:{n:"Thiên Hỏa Đồng Nhân",y:"Đồng lòng với người, lửa bốc lên hợp với trời. Cộng đồng, đồng chí hướng.",a:"Hợp tác công khai, quang minh chính đại thì lợi. Đồng người ở nơi rộng rãi, đừng kết bè phái nơi xó tối."},
14:{n:"Hỏa Thiên Đại Hữu",y:"Sở hữu lớn, mặt trời giữa trời soi vạn vật. Giàu có, được mùa, thịnh đạt.",a:"Có nhiều thì càng phải khiêm và biết chia. Ngăn ác dương thiện, thuận theo lẽ trời thì giữ được cái lớn."},
15:{n:"Địa Sơn Khiêm",y:"Khiêm nhường — núi cao náu mình dưới đất. Quẻ duy nhất 6 hào đều tốt.",a:"Càng tài giỏi càng cúi thấp thì càng được nâng lên. Việc gì lấy khiêm tốn làm đầu đều hanh thông trọn vẹn."},
16:{n:"Lôi Địa Dự",y:"Hân hoan, sấm rền trên đất báo mùa xuân. Thuận thời mà động, lòng người phấn chấn.",a:"Thời thuận để khởi động dự án, dựng người phụ tá, ra quân. Nhưng đừng để niềm vui thành đam mê trễ nải."},
17:{n:"Trạch Lôi Tùy",y:"Theo thời, tuỳ thuận. Sấm nấp trong đầm nghỉ đông; biết theo đúng người, đúng lúc.",a:"Buông cố chấp cá nhân, linh hoạt theo hoàn cảnh mới. Chọn đúng cái để theo thì hanh thông, không lỗi."},
18:{n:"Sơn Phong Cổ",y:"Đổ nát cần sửa — gió quẩn chân núi làm mọt sinh. Việc cũ hư hỏng do trì trệ.",a:"Can đảm sửa sai từ gốc, kể cả lỗi do đời trước để lại. Trước khi làm ba ngày tính kỹ, sau khi làm ba ngày theo dõi."},
19:{n:"Địa Trạch Lâm",y:"Tiến tới, giám sát, đến gần. Dương khí đang lớn dần; thời cơ đang mở.",a:"Chủ động tiếp cận, chăm sóc, dạy dỗ, mở mang. Nhưng nhớ: đến tháng tám sẽ có hung — thịnh rồi phải phòng suy."},
20:{n:"Phong Địa Quán",y:"Quan sát, chiêm ngưỡng. Gió thổi trên đất, xem xét khắp nơi; thời của nhìn và được nhìn.",a:"Dừng hành động để quan sát toàn cục và tự xét mình. Làm gương cho người dưới; quan sát sâu rồi hãy quyết."},
21:{n:"Hỏa Lôi Phệ Hạp",y:"Cắn xuyên vật cản. Có kẻ/điều ngáng trở giữa hai hàm răng — phải cắn đứt mới khép miệng được.",a:"Dùng biện pháp cứng rắn, kể cả pháp lý, để loại bỏ chướng ngại. Hình phạt công minh thì hanh thông."},
22:{n:"Sơn Hỏa Bí",y:"Trang sức, vẻ đẹp bề ngoài. Lửa chiếu chân núi làm cảnh vật lung linh — đẹp nhưng không đi xa được.",a:"Chăm chút hình thức là tốt cho việc nhỏ, nhưng đừng lấy vỏ thay ruột. Việc lớn cần chất thật."},
23:{n:"Sơn Địa Bác",y:"Bóc mòn, sụp lở. Âm leo lên bào mòn dương; núi đổ dần xuống đất — thời suy thoái.",a:"Không đi đâu lúc này thì hơn. Đừng gắng gượng chống đỡ; giữ hạt giống cuối cùng (quả lớn không bị ăn) chờ hồi sinh."},
24:{n:"Địa Lôi Phục",y:"Hồi phục, một hào dương trở lại. Đông chí — ánh sáng bắt đầu quay về sau ngày tối nhất.",a:"Điều tốt đang nhen nhóm trở lại: khởi đầu lại nhẹ nhàng, đừng ép tiến độ. Bảy ngày sẽ trở lại — kiên nhẫn với chu kỳ."},
25:{n:"Thiên Lôi Vô Vọng",y:"Không càn bậy, hồn nhiên đúng đạo. Hành động thuận thiên thì đại thành; trái lẽ thì gặp họa.",a:"Làm việc với động cơ trong sáng, không mưu cầu quá phận. Nếu tai ương đến không do lỗi mình — đừng chữa bậy, nó tự qua."},
26:{n:"Sơn Thiên Đại Súc",y:"Tích lũy lớn. Núi chứa trời — sức mạnh được nuôi và kiềm để dùng vào việc lớn.",a:"Học lời xưa, nuôi chí lớn, rèn bản lĩnh. Không ăn ở nhà (ra ngoài gánh việc chung) thì tốt; đủ lực rồi vượt sông lớn."},
27:{n:"Sơn Lôi Di",y:"Nuôi dưỡng, cái miệng. Xem người ta nuôi thân nuôi đức thế nào thì biết cát hung.",a:"Cẩn thận lời ra khỏi miệng và món ăn vào miệng. Tự nuôi mình bằng thứ lành mạnh, đừng thèm muốn phần của người."},
28:{n:"Trạch Phong Đại Quá",y:"Quá tải — xà nhà oằn cong. Việc lớn vượt sức thường, tình thế phi thường.",a:"Thời phi thường phải làm việc phi thường, nhưng cần chỗ dựa chắc. Dám đứng một mình không sợ, song đừng thêm gánh lên xà đã cong."},
29:{n:"Thuần Khảm",y:"Hiểm trùng hiểm — nước sâu tầng tầng. Gian nan liên tiếp, nhưng nước vẫn chảy qua mọi vực.",a:"Giữ lòng tin và sự thành thật làm phao. Đừng liều thoát nhanh; như nước, đầy chỗ trũng này rồi mới qua chỗ kế."},
30:{n:"Thuần Ly",y:"Lửa sáng, bám dính. Mặt trời mặt trăng nương vào trời mà sáng; con người nương lẽ phải mà rực rỡ.",a:"Nương tựa đúng chỗ thì phát sáng. Nuôi trâu cái (đức nhu thuận) thì cát; sáng mà không đốt cháy mình."},
31:{n:"Trạch Sơn Hàm",y:"Cảm ứng, rung động đôi bên. Đầm trên núi, khí giao hoà — quẻ của tình yêu chớm nở.",a:"Mở lòng đón nhận, cưới hỏi kết giao đều lợi. Cảm nhau bằng sự trống rỗng thành tâm, đừng toan tính."},
32:{n:"Lôi Phong Hằng",y:"Bền lâu, giữ đạo thường. Sấm gió theo nhau không đổi lối; vợ chồng, sự nghiệp cần sự thường hằng.",a:"Kiên trì con đường đã chọn, đừng đứng núi này trông núi nọ. Bền không phải là ì — là đổi mà không rời gốc."},
33:{n:"Thiên Sơn Độn",y:"Lui ẩn đúng lúc. Âm tiến dần, người khôn rút sớm khi còn rút đẹp được.",a:"Rút lui chiến thuật không phải thua cuộc. Buông việc đang xấu đi, giữ khoảng cách với tiểu nhân mà không tỏ ghét."},
34:{n:"Lôi Thiên Đại Tráng",y:"Cường tráng — sấm vang trên trời. Sức mạnh đang thịnh, khí thế dâng cao.",a:"Mạnh nhưng phải chính: đừng như dê húc giậu, kẹt sừng. Sức lớn dùng đúng lễ mới bền."},
35:{n:"Hỏa Địa Tấn",y:"Tiến lên như mặt trời mọc trên đất. Được bề trên tin dùng, thăng tiến rõ rệt.",a:"Thời tiến thân: xuất hiện, cống hiến, nhận nhiệm vụ. Tiến trong sáng sủa, không giành giật thì được thưởng nhiều lần."},
36:{n:"Địa Hỏa Minh Di",y:"Ánh sáng bị thương — mặt trời lặn vào lòng đất. Người tài gặp thời tối, bị vùi dập.",a:"Giấu sáng trong ngoài giữ khó nhọc mà chính. Đừng phô trí tuệ lúc này; như Cơ Tử giả ngây giữ mình chờ sáng."},
37:{n:"Phong Hỏa Gia Nhân",y:"Người trong nhà. Gió từ lửa ra — nề nếp gia đình lan thành phong hoá.",a:"Củng cố tổ ấm, ai đúng vai nấy, lời nói có thật chất. Sửa nhà trước rồi thiên hạ mới yên; lợi cho nữ chính bền."},
38:{n:"Hỏa Trạch Khuê",y:"Chia lìa, trái ngược. Lửa bốc lên đầm chảy xuống; hai ý cùng nhà mà khác hướng.",a:"Việc nhỏ vẫn làm được tốt; đừng cố ép hợp việc lớn khi lòng người đang khác nhau. Tìm điểm đồng trong dị."},
39:{n:"Thủy Sơn Kiển",y:"Gian truân, chân đi khó — nước hiểm trước mặt, núi chắn sau lưng.",a:"Đừng đâm đầu về hướng hiểm; lui về, tìm người giỏi mà theo, lợi hướng Tây Nam. Gặp khó quay về sửa mình."},
40:{n:"Lôi Thủy Giải",y:"Cởi mở, tan băng. Sấm mưa nổi lên, khí bế tắc được giải; hoạn nạn đang tháo nút.",a:"Tha thứ, xoá lỗi cũ, giải quyết nhanh gọn rồi trở về nhịp thường. Có việc cần làm thì làm sớm thì cát."},
41:{n:"Sơn Trạch Tổn",y:"Bớt đi để được. Bớt dưới đắp trên, bớt cái thừa nuôi cái thiếu — hy sinh có tính toán.",a:"Cắt giảm chi tiêu, ham muốn, cái tôi — thành tâm thì tổn mà vẫn cát. Hai giỏ cơm đạm bạc vẫn dâng cúng được."},
42:{n:"Phong Lôi Ích",y:"Tăng ích. Bớt trên thêm dưới, gió sấm giúp nhau tăng lực; thời được trợ giúp lớn.",a:"Thời tốt để đầu tư, vượt sông lớn, làm việc thiện. Thấy điều hay thì theo ngay, có lỗi thì sửa liền."},
43:{n:"Trạch Thiên Quải",y:"Quyết liệt loại trừ. Năm dương cùng trừ một âm — cái xấu cuối cùng phải bị công khai xử lý.",a:"Tố cáo minh bạch ở nơi công chính, nhưng đừng dùng bạo lực. Cảnh giác: đừng khinh địch dù nó chỉ còn một."},
44:{n:"Thiên Phong Cấu",y:"Gặp gỡ bất ngờ — một âm mới sinh lẻn vào dưới năm dương. Cám dỗ nhỏ mà sức lan lớn.",a:"Cẩn thận với mối quan hệ/cơ hội quá hấp dẫn xuất hiện đột ngột. Chớ cưới người con gái quá mạnh (điều nhỏ sẽ lấn quyền)."},
45:{n:"Trạch Địa Tụy",y:"Tụ họp. Nước tụ trên đất thành đầm; người tụ về nơi có đức lớn.",a:"Thời gom sức mạnh tập thể: họp mặt, cúng tế, ra mắt người lớn. Chuẩn bị cả đề phòng — đông người ắt sinh bất trắc."},
46:{n:"Địa Phong Thăng",y:"Vươn lên như cây non trong đất, lớn dần thành cao lớn. Thăng tiến từng bước chắc chắn.",a:"Tích tiểu thành đại, gặp người lớn thì cứ đến gặp, đừng lo. Tiến về phương Nam (hướng sáng) thì cát."},
47:{n:"Trạch Thủy Khốn",y:"Khốn cùng — đầm cạn nước. Bị vây hãm, lời nói không ai tin.",a:"Thời khốn thì nói ít làm nhiều, giữ vững chí trong cùng quẫn. Người lớn giữ chính thì cát; khốn mà không mất niềm vui nội tâm."},
48:{n:"Thủy Phong Tỉnh",y:"Cái giếng. Làng đổi giếng không đổi; nguồn nuôi dưỡng chung không cạn không tràn.",a:"Chăm sóc lại nguồn lực cốt lõi (kỹ năng, sức khoẻ, đội ngũ). Giếng tốt mà không ai múc thì phí — hãy để người dùng được mình."},
49:{n:"Trạch Hỏa Cách",y:"Cách mạng, thay đổi lớn. Lửa trong đầm — hai thứ khắc nhau buộc phải biến đổi.",a:"Thay đổi lớn sẽ thành nếu đúng thời và được lòng tin. Đợi đúng ngày mới cải; đổi xong thì hối hận tan biến."},
50:{n:"Hỏa Phong Đỉnh",y:"Cái vạc — nấu chín, dưỡng hiền tài, lập trật tự mới sau cách mạng.",a:"Thời xây dựng nền nếp mới, nuôi người giỏi. Nguyên cát, hanh thông; giữ vạc vững, đừng để gãy chân đổ thức ăn."},
51:{n:"Thuần Chấn",y:"Sấm động liên hồi. Biến cố đến ầm ầm khiến kinh sợ, nhưng sau tiếng sấm mọi vật bừng tỉnh.",a:"Hoảng sợ lúc đầu rồi cười nói như thường — người biết sợ mà không loạn sẽ trưởng thành. Xem biến cố là tiếng chuông tỉnh thức."},
52:{n:"Thuần Cấn",y:"Núi tĩnh lặng. Dừng đúng chỗ cần dừng; đứng yên như núi, không thấy người, không thấy mình.",a:"Thời của thiền định, giữ lưng yên (không vọng động). Biết dừng là đạo lớn: dừng suy nghĩ quá khứ và lo lắng tương lai."},
53:{n:"Phong Sơn Tiệm",y:"Tiến dần dần. Cây trên núi lớn từng phân; chim hồng bay từ bến lên cao theo thứ tự.",a:"Đường dài đi bằng những bước nhỏ đúng trình tự — như cưới hỏi phải đủ lễ. Đừng đốt cháy giai đoạn."},
54:{n:"Lôi Trạch Quy Muội",y:"Em gái về nhà chồng — kết hợp không đúng vị, danh phận thiệt thòi.",a:"Vị thế của bạn trong việc này không thuận; tiến tới thì xấu. Nếu buộc phải tham gia, chấp nhận vai phụ và giữ đức lâu dài."},
55:{n:"Lôi Hỏa Phong",y:"Thịnh đại như mặt trời đứng bóng. Sấm và lửa cùng rực — đỉnh cao huy hoàng.",a:"Tận hưởng và toả sáng ngay bây giờ, đừng lo lắng ngày tà. Nhưng biết rằng trăng đầy sẽ khuyết — chuẩn bị cho chu kỳ sau."},
56:{n:"Hỏa Sơn Lữ",y:"Lữ khách nơi đất lạ. Lửa cháy trên núi không ở lâu một chỗ; thân phận tạm trú.",a:"Ở nơi/vai trò mới hãy khiêm cung, mềm mỏng, việc nhỏ thì hanh. Đừng gây chuyện nơi đất khách; giữ hành trang gọn nhẹ."},
57:{n:"Thuần Tốn",y:"Gió len lỏi khắp nơi. Thuận nhập, thâm nhập nhẹ nhàng; mệnh lệnh nhắc lại nhiều lần mới thấm.",a:"Kiên trì tác động nhỏ, lặp lại — như gió lâu ngày mòn đá. Việc nhỏ hanh thông; cần theo người lớn dẫn dắt."},
58:{n:"Thuần Đoài",y:"Đầm nối đầm — niềm vui giao hoà. Vui vẻ, trao đổi, bạn bè cùng học cùng luyện.",a:"Dùng niềm vui chân thật để kết nối và dẫn dắt, dân quên cả nhọc. Nhưng vui phải chính đáng, đừng vui theo kiểu dua nịnh."},
59:{n:"Phong Thủy Hoán",y:"Tan rã, lan toả. Gió thổi trên nước làm băng tan; sự cứng đọng, chia rẽ được thổi tan.",a:"Phá tan sự ích kỷ, hiềm khích bằng việc chung lớn lao. Thời tốt để hoà giải, vượt sông lớn, quy tụ lòng người."},
60:{n:"Thủy Trạch Tiết",y:"Tiết chế, chừng mực. Đầm chứa nước có hạn; sống có tiết độ như đốt tre có mắt.",a:"Đặt giới hạn cho chi tiêu, lời nói, ham muốn thì hanh thông. Nhưng tiết chế khắc khổ quá thì không bền — đừng ép mình đến khổ."},
61:{n:"Phong Trạch Trung Phu",y:"Thành tín từ trong lòng. Gió trên đầm, lòng tin cảm hoá được cả cá heo (vật vô tri).",a:"Sự chân thành là sức mạnh lớn nhất của bạn lúc này. Giữ chữ tín tuyệt đối thì việc hiểm mấy cũng vượt được."},
62:{n:"Lôi Sơn Tiểu Quá",y:"Quá nhỏ — chim bay không nên lên cao, nên xuống thấp. Thời chỉ hợp việc nhỏ.",a:"Làm việc nhỏ chu đáo hơn mức thường (cung kính hơn, tiết kiệm hơn, đau buồn thành thật hơn). Chớ mưu việc lớn lúc này."},
63:{n:"Thủy Hỏa Ký Tế",y:"Đã hoàn thành — nước trên lửa, nồi cơm đã chín. Mọi hào đều đúng vị; viên mãn nhưng là đỉnh của dốc.",a:"Việc đã xong: củng cố, phòng ngừa rủi ro hậu kỳ. Ban đầu cát, về sau dễ loạn — đừng ngủ quên trên thành công."},
64:{n:"Hỏa Thủy Vị Tế",y:"Chưa hoàn thành — con cáo nhỏ qua sông gần tới bờ thì ướt đuôi. Còn một đoạn cuối chưa xong.",a:"Sắp thành nhưng chưa thành: thận trọng gấp đôi ở bước cuối. Phân định rõ việc và người, sắp xếp lại rồi hoàn tất."}
};
/* Ma trận Văn Vương: HEXMAP[quẻ_dưới][quẻ_trên] = số quẻ. Trigram index: bit hào 1-2-3 (dưới lên), 1=dương */
/* index: 0=Khôn(000) 1=Chấn(100) 2=Khảm(010) 3=Đoài(110) 4=Cấn(001) 5=Ly(101) 6=Tốn(011) 7=Càn(111) — bit0=hào dưới */
const TRIGRAMS = ["Khôn ☷","Chấn ☳","Khảm ☵","Đoài ☱","Cấn ☶","Ly ☲","Tốn ☴","Càn ☰"];
const HEXMAP = {
7:{7:1,1:34,2:5,4:26,0:11,6:9,5:14,3:43},
1:{7:25,1:51,2:3,4:27,0:24,6:42,5:21,3:17},
2:{7:6,1:40,2:29,4:4,0:7,6:59,5:64,3:47},
4:{7:33,1:62,2:39,4:52,0:15,6:53,5:56,3:31},
0:{7:12,1:16,2:8,4:23,0:2,6:20,5:35,3:45},
6:{7:44,1:32,2:48,4:18,0:46,6:57,5:50,3:28},
5:{7:13,1:55,2:63,4:22,0:36,6:37,5:30,3:49},
3:{7:10,1:54,2:60,4:41,0:19,6:61,5:38,3:58}
};

/* ---------- SAO TỬ VI ---------- */
const SAO_INFO = {
"Tử Vi":"Đế tinh, chủ quyền uy, phúc đức. Người có Tử Vi thủ mệnh thường đĩnh đạc, có chí lãnh đạo, được người nể trọng; cần bề tôi tốt (Tả Hữu, Xương Khúc) mới phát hết.",
"Thiên Cơ":"Sao trí tuệ, mưu lược, khéo xoay xở. Óc phân tích nhanh, thích máy móc – kỹ thuật – kế hoạch; đa mưu nhưng dễ nghĩ nhiều, lo xa.",
"Thái Dương":"Mặt trời — quang minh, nhiệt huyết, thích giúp người, hợp công danh. Sáng nhất khi ở Tỵ–Ngọ (ban ngày); nam mệnh chủ sự nghiệp, nữ mệnh chủ chồng.",
"Vũ Khúc":"Sao tài tinh, cương nghị, giỏi về tiền bạc – kinh doanh – kỹ nghệ. Tính quyết đoán, ít lời, trọng thực tế; dễ khô khan trong tình cảm.",
"Thiên Đồng":"Sao phúc tinh, ôn hoà, hưởng thụ, trẻ trung. Người nhân hậu, thích an nhàn, nghệ thuật; thiếu bền chí, hợp môi trường ít cạnh tranh.",
"Liêm Trinh":"Sao tù tinh kiêm đào hoa thứ, cá tính mạnh, dứt khoát, trọng nguyên tắc. Đắc cách thì thanh liêm chính trực; hãm thì dễ vướng thị phi, pháp lý.",
"Thiên Phủ":"Kho trời — bảo thủ, nhân hậu, giỏi giữ của, ổn định. Người có Thiên Phủ thủ mệnh sống chắc chắn, được quý nhân giúp, ít sóng gió lớn.",
"Thái Âm":"Mặt trăng — dịu dàng, thẩm mỹ, chủ điền sản và mẹ/vợ. Sáng nhất ở Dậu–Hợi (ban đêm); tâm hồn tinh tế, hợp văn chương, bất động sản.",
"Tham Lang":"Sao đào hoa, ham muốn, đa tài đa nghệ, giao thiệp rộng. Đắc cách thì thành công về giao tế – kinh doanh; hãm thì mê chơi, thị phi tình ái.",
"Cự Môn":"Sao ám tinh, chủ cái miệng: ăn nói, tranh biện, dạy học, pháp lý. Đắc cách thì sống bằng lời nói mà thành danh; hãm thì dễ khẩu thiệt, kiện cáo.",
"Thiên Tướng":"Ấn tinh — người phụ tá trung thành, công bằng, trọng danh dự, thích che chở kẻ yếu. Tính cách phụ thuộc nhiều vào sao đồng cung và xung chiếu.",
"Thiên Lương":"Thọ tinh, sao che chở — ông thầy, thầy thuốc, người cứu giải. Nhân hậu, thích dạy bảo, gặp nạn thường có cứu; hợp nghề y, giáo, tâm linh.",
"Thất Sát":"Tướng tinh xung phong — quyết liệt, dám làm dám chịu, đời nhiều phen lập nghiệp lại. Uy dũng, không sợ khó; cần tránh nóng vội cực đoan.",
"Phá Quân":"Sao tiên phong phá cũ lập mới — đời nhiều thay đổi lớn, hao rồi lại tạo. Sáng tạo, gan lì, hợp nghề khai phá; kỵ sự trì trệ lặp lại.",
"Tả Phụ":"Quý nhân phù trợ bên trái — được người giúp đỡ, giỏi tổ chức hậu cần.",
"Hữu Bật":"Quý nhân phù trợ bên phải — nhân duyên tốt, hay được nâng đỡ âm thầm.",
"Văn Xương":"Sao văn tinh — giỏi chữ nghĩa, thi cử, giấy tờ, khoa bảng.",
"Văn Khúc":"Sao văn tinh — tài ăn nói, nghệ thuật, âm nhạc, khéo léo giao tiếp.",
"Lộc Tồn":"Sao tài lộc bền — có của để dành, được hưởng bổng lộc; đi đôi với tính cẩn thận.",
"Kình Dương":"Sao hình tinh — sắc bén, cạnh tranh, dễ va chạm; đắc cách thành dũng lược.",
"Đà La":"Sao trì trệ — việc hay lần lữa, dây dưa; dạy con người sự kiên nhẫn.",
"Địa Không":"Sao không vong — hao tán bất ngờ, nghĩ khác người; hợp tu tâm, triết học.",
"Địa Kiếp":"Sao kiếp sát — thăng trầm về vật chất; nhắc giữ mình trước cám dỗ đầu cơ.",
"Thiên Khôi":"Quý nhân dương — được người trên nâng đỡ công khai, thi cử hanh thông.",
"Thiên Việt":"Quý nhân âm — được giúp đỡ kín đáo, gặp lành trong nguy.",
"Hỏa Tinh":"Sao nóng — bộc phát, thành bại nhanh; đi với Tham Lang thành cách phát mạnh.",
"Linh Tinh":"Sao âm hỏa — lì lợm, chịu đựng, phát chậm mà bền hơn Hỏa Tinh.",
"Hóa Lộc":"Hóa khí tài lộc — chủ tiền bạc, may mắn vật chất trong năm/cung có nó.",
"Hóa Quyền":"Hóa khí quyền uy — chủ thăng tiến, nắm quyền, quyết đoán.",
"Hóa Khoa":"Hóa khí khoa danh — chủ danh tiếng, học vấn, được che chở khỏi tai tiếng.",
"Hóa Kỵ":"Hóa khí ghen kỵ — chủ trắc trở, thị phi; nhắc cẩn trọng lĩnh vực cung có nó."
};
const CUNG_INFO = {
"Mệnh":"Cung gốc — tính cách, hình dáng, năng lực, hướng đời tổng quát.",
"Phụ Mẫu":"Quan hệ với cha mẹ, sự thừa hưởng, người bề trên.",
"Phúc Đức":"Phúc phần dòng họ, đời sống tinh thần, thọ yểu, họ hàng.",
"Điền Trạch":"Nhà cửa, đất đai, tài sản cố định, môi trường sống.",
"Quan Lộc":"Sự nghiệp, công danh, nghề phù hợp, quan hệ với cấp trên.",
"Nô Bộc":"Bạn bè, đồng nghiệp, người cộng sự, người dưới quyền.",
"Thiên Di":"Ra ngoài xã hội: cơ hội nơi xa, cách người đời nhìn mình.",
"Tật Ách":"Sức khoẻ, bệnh tật tiềm ẩn, tai ách cần phòng.",
"Tài Bạch":"Tiền bạc, cách kiếm và giữ tiền, tài vận.",
"Tử Tức":"Con cái, học trò, các 'đứa con tinh thần' (tác phẩm, dự án).",
"Phu Thê":"Hôn nhân, người phối ngẫu, kiểu tình duyên.",
"Huynh Đệ":"Anh chị em, bạn chí cốt, quan hệ ngang hàng."
};

/* ---------- CHIÊM TINH — 12 CUNG HOÀNG ĐẠO ---------- */
const ZODIAC = [
{n:"Bạch Dương (Aries)",g:"♈",d:"21/3 – 19/4",e:"Lửa",q:"Thống lĩnh",p:"Sao Hỏa",m:"Tiên phong, bộc trực, hành động trước nghĩ sau. Năng lượng khởi đầu mạnh mẽ, ghét chờ đợi; cần học sự kiên nhẫn và lắng nghe."},
{n:"Kim Ngưu (Taurus)",g:"♉",d:"20/4 – 20/5",e:"Đất",q:"Kiên định",p:"Sao Kim",m:"Bền bỉ, thực tế, yêu cái đẹp và sự an toàn vật chất. Trung thành nhưng cứng đầu; giá trị sống xoay quanh sự ổn định và hưởng thụ có gu."},
{n:"Song Tử (Gemini)",g:"♊",d:"21/5 – 20/6",e:"Khí",q:"Linh hoạt",p:"Sao Thủy",m:"Tò mò, lanh lợi, giao tiếp là hơi thở. Đa nhiệm, hài hước, dễ chán; cần chiều sâu để không thành 'biết mỗi thứ một ít'."},
{n:"Cự Giải (Cancer)",g:"♋",d:"21/6 – 22/7",e:"Nước",q:"Thống lĩnh",p:"Mặt Trăng",m:"Nhạy cảm, che chở, gắn bó gia đình. Trực giác mạnh, nhớ lâu; vỏ cứng ruột mềm, cần cảm giác an toàn để mở lòng."},
{n:"Sư Tử (Leo)",g:"♌",d:"23/7 – 22/8",e:"Lửa",q:"Kiên định",p:"Mặt Trời",m:"Hào phóng, ấm áp, sinh ra để toả sáng và dẫn dắt. Tự trọng cao, thích được ghi nhận; bài học là toả sáng mà không che mất người khác."},
{n:"Xử Nữ (Virgo)",g:"♍",d:"23/8 – 22/9",e:"Đất",q:"Linh hoạt",p:"Sao Thủy",m:"Tinh tế, chu toàn, óc phân tích sắc bén, thích phục vụ hữu ích. Cầu toàn với mình lẫn người; cần học chấp nhận sự chưa hoàn hảo."},
{n:"Thiên Bình (Libra)",g:"♎",d:"23/9 – 22/10",e:"Khí",q:"Thống lĩnh",p:"Sao Kim",m:"Duyên dáng, công bằng, sống vì các mối quan hệ hài hoà. Giỏi ngoại giao, thẩm mỹ tốt; điểm yếu là do dự vì muốn đẹp lòng đôi bên."},
{n:"Bọ Cạp (Scorpio)",g:"♏",d:"23/10 – 21/11",e:"Nước",q:"Kiên định",p:"Sao Diêm Vương",m:"Sâu sắc, mãnh liệt, nhìn thấu bản chất. Trung thành tuyệt đối, yêu–ghét rõ ràng; sức mạnh nằm ở khả năng tái sinh sau khủng hoảng."},
{n:"Nhân Mã (Sagittarius)",g:"♐",d:"22/11 – 21/12",e:"Lửa",q:"Linh hoạt",p:"Sao Mộc",m:"Phóng khoáng, lạc quan, khát khao chân trời và ý nghĩa. Thẳng thắn đến vô tư; cần học chữ 'cam kết' cho tự do có gốc rễ."},
{n:"Ma Kết (Capricorn)",g:"♑",d:"22/12 – 19/1",e:"Đất",q:"Thống lĩnh",p:"Sao Thổ",m:"Kỷ luật, tham vọng, leo núi bền bỉ từng bậc. Trưởng thành sớm, trọng trách nhiệm; càng có tuổi càng thảnh thơi và hài hước."},
{n:"Bảo Bình (Aquarius)",g:"♒",d:"20/1 – 18/2",e:"Khí",q:"Kiên định",p:"Sao Thiên Vương",m:"Độc lập, cấp tiến, tư duy vượt khuôn. Yêu nhân loại theo cách riêng, quý tự do tư tưởng; đôi khi gần mà xa với người thân cận."},
{n:"Song Ngư (Pisces)",g:"♓",d:"19/2 – 20/3",e:"Nước",q:"Linh hoạt",p:"Sao Hải Vương",m:"Mơ mộng, trắc ẩn, ranh giới mỏng giữa mình và người. Nghệ sĩ tính, trực giác gần như ngoại cảm; cần neo thực tế để không trôi."}
];
const MOON_SIGN_NOTE = {
"Lửa":"Mặt Trăng ở cung Lửa: cảm xúc bùng nổ nhanh, cần hành động để giải toả; hồi phục cũng nhanh.",
"Đất":"Mặt Trăng ở cung Đất: cảm xúc ổn định, cần sự an toàn vật chất và thói quen để thấy yên tâm.",
"Khí":"Mặt Trăng ở cung Khí: xử lý cảm xúc bằng lời nói và lý trí, cần được trò chuyện, chia sẻ.",
"Nước":"Mặt Trăng ở cung Nước: cảm xúc sâu và thấm lâu, trực giác mạnh, cần không gian riêng để lắng."
};
